version: '2'
services:

  kafka:
    container_name: kafka
    image: ches/kafka:0.10.1.0
    depends_on:
      - zookeeper
    environment:
      ZOOKEEPER_IP: zookeeper
      ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - '9092:9092'  # Kafka broker
      - '7203:7203'  # JMX
    volumes:
      - kafka-data:/data
      - kafka-logs:/logs  
  zookeeper:
    container_name: zookeeper
    image: jplock/zookeeper:3.4.8
    restart: unless-stopped
    ports:
      - '2181:2181'
volumes:
  kafka-data:
  kafka-logs: